// <auto-generated />
namespace I_S_L_A_M.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class VendStars : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VendStars));
        
        string IMigrationMetadata.Id
        {
            get { return "202202141106155_VendStars"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
